export * from "./icon"

// SVG
export * from "./SVG/close"
export * from "./SVG/check-circle"
export * from "./SVG/chevron-down"
export * from "./SVG/chevron-down-outline"
export * from "./SVG/chevron-up"
export * from "./SVG/cross-circle"
export * from "./SVG/cross"
export * from "./SVG/dashboard"
export * from "./SVG/exclamation"
export * from "./SVG/google"
export * from "./SVG/login"
export * from "./SVG/logout"
export * from "./SVG/menu"
export * from "./SVG/moon"
export * from "./SVG/info"
export * from "./SVG/profile"
export * from "./SVG/question-circle"
export * from "./SVG/search"
export * from "./SVG/selector"
export * from "./SVG/spinner"
export * from "./SVG/sun"
export * from "./SVG/user-circle"
